# Generated by Django 5.2.7 on 2025-11-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoleImageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, unique=True, verbose_name='Role Name')),
                ('max_images', models.PositiveIntegerField(default=5, verbose_name='Max Images')),
            ],
            options={
                'verbose_name': 'Role Image Limit',
                'verbose_name_plural': 'Role Image Limits',
                'ordering': ['role_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=128, verbose_name='Site Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logo/', verbose_name='Logo')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer Text')),
                ('max_images_per_ad', models.PositiveIntegerField(default=5, verbose_name='Max Images Per Ad')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
