# Generated by Django 5.2.7 on 2025-11-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Credit Card, Crypto', max_length=100, verbose_name='Display Name')),
                ('provider_id', models.CharField(choices=[('stripe', 'Stripe'), ('nowpayments', 'Crypto (NowPayments)')], max_length=50, unique=True, verbose_name='Provider ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Provider specific config (public keys, etc)', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from the payment provider (e.g. sub_123 or payment_id)', max_length=100, null=True, verbose_name='External Subscription ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.paymentmethod'),
        ),
    ]
