"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from django_settings_env import Env

env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Note: `django_settings_env.Env` prefixes variables with `DJANGO_` by default.
# Calling `env(...)` without a name will resolve using the setting name, so
# set `DJANGO_SECRET_KEY` in your environment (or use `DJANGO_SECRET_KEY` in
# your `.env` file). This value will populate Django's `SECRET_KEY`.
SECRET_KEY = env(
    default="django-insecure-)!f7(dxn2a#%!lh-9a#0z7sj$733f)1%u-0(d#+rc#1+*p3b7*"
)

DEBUG = env(default=False)

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0"]

# ---------------------------------------------------------------------------
# Security settings (use environment to override in production)
# Uses `django_settings_env.Env` via `env(...)` already imported above.
# Change values via environment variables in production, e.g.
#   DJANGO_SECRET_KEY, DJANGO_DEBUG, DJANGO_SECURE_SSL_REDIRECT, etc.
# ---------------------------------------------------------------------------
# Redirect all non-HTTPS requests to HTTPS in production (True/False)
# Use `django_settings_env.Env` helpers so behavior matches your environment
# (Env prefixes names with DJANGO_ by default).
# Redirect all non-HTTPS requests to HTTPS in production (True/False)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)

# Use secure cookies so they are only sent over HTTPS
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)

# HTTP Strict Transport Security (HSTS). Start small (3600) for testing,
# then set to 31536000 (1 year) when you're ready for production.
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

# If your app runs behind a reverse proxy (load balancer) that terminates TLS,
# enable this and ensure the proxy sets X-Forwarded-Proto. Uses DJANGO_USE_PROXY_SSL_HEADER
if env.bool("USE_PROXY_SSL_HEADER", default=False):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core",
    "apps.subscriptions",  # subscriptions app
    "django.contrib.sites",  # added for allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    # ... include the providers you want to enable:
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.instagram",
    "imagekit",
    "tree_queries",
    "guardian",
    "widget_tweaks",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es"

LANGUAGES = [
    # ('en', _('English')),
    ("es", _("Spanish")),
]

# 📂 Path where the .po and .mo translation files will be stored
LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# During development, Django will serve static files from these directories
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# In production, collectstatic will copy files here
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication backends for allauth
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
    # django-guardian object-permission backend
    "guardian.backends.ObjectPermissionBackend",
]

# Provider specific settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("GOOGLE_CLIENT_ID", default=""),
            "secret": env("GOOGLE_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
    "facebook": {
        "APP": {
            "client_id": env("FACEBOOK_CLIENT_ID", default=""),
            "secret": env("FACEBOOK_CLIENT_SECRET", default=""),
            "key": "",
        },
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "INIT_PARAMS": {"cookie": True},
        "FIELDS": [
            "id",
            "first_name",
            "last_name",
            "middle_name",
            "name",
            "name_format",
            "picture",
            "short_name",
        ],
        "EXCHANGE_TOKEN": True,
    },
    "instagram": {
        "APP": {
            "client_id": env("INSTAGRAM_CLIENT_ID", default=""),
            "secret": env("INSTAGRAM_CLIENT_SECRET", default=""),
            "key": "",
        },
        "SCOPE": ["user_profile", "user_media"],
    },
}


SITE_ID = 1
LOGIN_REDIRECT_URL = "/"
ACCOUNT_EMAIL_VERIFICATION = "optional"
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = [
    "email*",
    "username*",
    "password1*",
    "password2*",
]

# django-guardian configuration
ANONYMOUS_USER_ID = -1

# Media (for uploaded ad images)
MEDIA_URL = "/media/"
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Email settings
DEFAULT_FROM_EMAIL = env(default="noreply@isowo.com")
EMAIL_BACKEND = env(default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env(default="localhost")
EMAIL_PORT = env(default=587)
EMAIL_USE_TLS = env(default=True)
EMAIL_HOST_USER = env(default="")
EMAIL_HOST_PASSWORD = env(default="")

# Stripe Configuration
STRIPE_PUBLISHABLE_KEY = env("STRIPE_PUBLISHABLE_KEY", default="pk_test_placeholder")
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="sk_test_placeholder")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="whsec_placeholder")

# Django REST Framework defaults (used by core limits endpoint throttling)
REST_FRAMEWORK = {
    # Throttle rates can be tuned for your deployment; these are sensible defaults
    # Anon: 60 requests per minute, Authenticated users: 600 requests per minute
    "DEFAULT_THROTTLE_RATES": {"anon": "60/min", "user": "600/min"},
}
